
classdef JointTarget < ros.Message
    %JointTarget MATLAB implementation of ob1_arm_control/JointTarget
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ob1_arm_control/JointTarget' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '133ac1ee056e983bab7d9619a1e96ecf' % The MD5 Checksum of the message definition
        PropertyList = { 'JointTarget_' } % List of non-constant message properties
        ROSPropertyList = { 'joint_target' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        JointTarget_
    end
    methods
        function set.JointTarget_(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'JointTarget', 'JointTarget_');
            obj.JointTarget_ = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ob1_arm_control.JointTarget.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ob1_arm_control.JointTarget(strObj);
        end
    end
end
