<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="arm_with_pedestal">

    <xacro:property name="arm_name" value="arm1" />
    <xacro:property name="base_name" value="base" />
    <xacro:property name="width" value="0.5" />
    <xacro:property name="height" value="1.7" />
    
    <xacro:include filename="$(find ob1_arm_description)/urdf/ob1_arm.xacro"/>
    <xacro:include filename="$(find ob1_arm_description)/urdf/mobile_base.xacro"/>
    <xacro:include filename="$(find ob1_arm_description)/urdf/ob1_arm_gazebo.xacro"/>
    
    <xacro:macro name="pedestal">
        <link name="torso">
            <visual>
            <origin rpy="0 0 0" xyz="0 0 ${height/2}"/>
            <geometry>
                <box size="${width} ${width} ${height}"/>
            </geometry>
            </visual>

            <!-- <collision>
            <origin rpy="0 0 0" xyz="0 0 ${height/2}"/>
            <geometry>
                <box size="${width} ${width} ${height}"/>
            </geometry>
            </collision> -->

            <inertial>
                <mass value="100" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="0.004" ixy="0.001" ixz="0" iyy="0.006" iyz="0" izz="0.007" />
            </inertial>
        </link>

        <joint name="hip_torso_joint" type="fixed">
            <parent link="tele_hip_link"/>
            <child link="torso"/>
            <origin xyz="0 0 0.2" rpy="0 0 0"/>
        </joint>

        <joint name="torso_base_joint" type="continuous">
            <origin rpy="${-pi/2} 0 0" xyz="0 ${width/2} ${height*2/3}"/>
            <axis xyz="0 0 1"/>
            <limit effort="1000.0" lower="${radians(-180)}" upper="${radians(180)}" velocity="0.5"/>
            <parent link="torso" />
            <child link="${arm_name}_base_link" />
            <dynamics D="1" K="7000" mu_coulomb="0" mu_viscous="16" damping="0.003" friction="0.0"/>
        </joint>

        

        <link name="tele_hip_link">
            <visual>
            <geometry>
                <cylinder length="0.2" radius="0.05"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0.1"/>
            </visual>
            <collision>
            <geometry>
                <cylinder length="0.2" radius="0.05"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0.1"/>
            </collision>
            <inertial>
                <mass value="25" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="0.1" ixy="0.1" ixz="0.1" iyy="0.1" iyz="0.1" izz="0.1" />
            </inertial>
        </link>

        <joint name="tele_hip_joint" type="prismatic">
            <parent link="base_link"/>
            <child link="tele_hip_link"/>
            <axis xyz="0 0 1" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <limit lower="0" upper="0.15" velocity="0.1" effort="1.0" />
        </joint>

        

        <link name="camera_link">
            <visual>
            <origin rpy="${-pi/2} 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 0.1"/>
            </geometry>
            </visual>
            <inertial>
                <mass value="1" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <inertia ixx="0.1" ixy="0.1" ixz="0.1" iyy="0.1" iyz="0.1" izz="0.1" />
            </inertial>
        </link>

        <joint name="torso_camera_link_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 ${width/2} ${height+0.1}"/>
            <parent link="torso" />
            <child link="camera_link" />
        </joint>
<!-- 
        <gazebo>
            <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>
        </gazebo> -->

        <!-- camera description adapted from http://gazebosim.org/tutorials?tut=ros_gzplugins#Pluginsavailableingazebo_plugins -->
        <gazebo reference="camera_link">
            <sensor name="depth_camera" type="depth">
                <update_rate>20</update_rate>
                <camera>
                <horizontal_fov>1.047198</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>3</far>
                </clip>
                </camera>
                <plugin name="kinetic_camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <updateRate>1.0</updateRate>
                <cameraName>placeholder_camera_ir</cameraName>
                <imageTopicName>/placeholder_camera/color/image_raw</imageTopicName>
                <cameraInfoTopicName>/placeholder_camera/color/camera_info</cameraInfoTopicName>
                <depthImageTopicName>/placeholder_camera/depth/image_raw</depthImageTopicName>
                <depthImageInfoTopicName>/placeholder_camera/depth/camera_info</depthImageInfoTopicName>
                <pointCloudTopicName>/placeholder_camera/depth/points</pointCloudTopicName>
                <frameName>placeholder_camera_link</frameName>
                <pointCloudCutoff>0.5</pointCloudCutoff>
                <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
                <distortionK1>0.00000001</distortionK1>
                <distortionK2>0.00000001</distortionK2>
                <distortionK3>0.00000001</distortionK3>
                <distortionT1>0.00000001</distortionT1>
                <distortionT2>0.00000001</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
                </plugin>
            </sensor>
            </gazebo>

    </xacro:macro>
    <xacro:mobile_base base_name="${base_name}"/>
    <xacro:arm arm_name="${arm_name}"/>
    <xacro:pedestal/>
</robot>