sensors:
  - filtered_cloud_topic: ""
    max_range: 5.0
    max_update_rate: ""
    padding_offset: 0.1
    padding_scale: 1.0
    point_cloud_topic: /arm1_camera/depth/points
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater