
classdef armCmd < ros.Message
    %armCmd MATLAB implementation of ob1_arm_hw_interface/armCmd
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ob1_arm_hw_interface/armCmd' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '8b54c869722a6f46d221c71294caa2ad' % The MD5 Checksum of the message definition
        PropertyList = { 'Vel' 'Angle' 'MsgSendCtr' 'NumJoints' } % List of non-constant message properties
        ROSPropertyList = { 'vel' 'angle' 'msg_send_ctr' 'num_joints' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Vel
        Angle
        MsgSendCtr
        NumJoints
    end
    methods
        function set.Vel(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 6};
            validateattributes(val, validClasses, validAttributes, 'armCmd', 'Vel');
            obj.Vel = single(val);
        end
        function set.Angle(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 6};
            validateattributes(val, validClasses, validAttributes, 'armCmd', 'Angle');
            obj.Angle = single(val);
        end
        function set.MsgSendCtr(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'armCmd', 'MsgSendCtr');
            obj.MsgSendCtr = int32(val);
        end
        function set.NumJoints(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'armCmd', 'NumJoints');
            obj.NumJoints = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ob1_arm_hw_interface.armCmd.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ob1_arm_hw_interface.armCmd(strObj);
        end
    end
end
