
classdef MatlabIKServiceRequest < ros.Message
    %MatlabIKServiceRequest MATLAB implementation of ob1_arm_control/MatlabIKServiceRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ob1_arm_control/MatlabIKServiceRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ad09fc55b0d494343b290d861e0efa46' % The MD5 Checksum of the message definition
        PropertyList = { 'PoseTarget' 'Tolerance' } % List of non-constant message properties
        ROSPropertyList = { 'pose_target' 'tolerance' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        PoseTarget
        Tolerance
    end
    methods
        function set.PoseTarget(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'MatlabIKServiceRequest', 'PoseTarget');
            obj.PoseTarget = double(val);
        end
        function set.Tolerance(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'MatlabIKServiceRequest', 'Tolerance');
            obj.Tolerance = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ob1_arm_control.MatlabIKServiceRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ob1_arm_control.MatlabIKServiceRequest(strObj);
        end
    end
end
