
classdef MatlabIKServiceResponse < ros.Message
    %MatlabIKServiceResponse MATLAB implementation of ob1_arm_control/MatlabIKServiceResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ob1_arm_control/MatlabIKServiceResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'bec3ec873883402ec62934e02f51a48f' % The MD5 Checksum of the message definition
        PropertyList = { 'Result' 'Error' 'Joints' } % List of non-constant message properties
        ROSPropertyList = { 'result' 'error' 'joints' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Result
        Error
        Joints
    end
    methods
        function set.Result(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'MatlabIKServiceResponse', 'Result');
            obj.Result = char(val);
        end
        function set.Error(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'MatlabIKServiceResponse', 'Error');
            obj.Error = double(val);
        end
        function set.Joints(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'MatlabIKServiceResponse', 'Joints');
            obj.Joints = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ob1_arm_control.MatlabIKServiceResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ob1_arm_control.MatlabIKServiceResponse(strObj);
        end
    end
end
