// Generated by gencpp from file ob1_arm_control/JointTarget.msg
// DO NOT EDIT!


#ifndef OB1_ARM_CONTROL_MESSAGE_JOINTTARGET_H
#define OB1_ARM_CONTROL_MESSAGE_JOINTTARGET_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ob1_arm_control
{
template <class ContainerAllocator>
struct JointTarget_
{
  typedef JointTarget_<ContainerAllocator> Type;

  JointTarget_()
    : joint_target()  {
    }
  JointTarget_(const ContainerAllocator& _alloc)
    : joint_target(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joint_target_type;
  _joint_target_type joint_target;





  typedef boost::shared_ptr< ::ob1_arm_control::JointTarget_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ob1_arm_control::JointTarget_<ContainerAllocator> const> ConstPtr;

}; // struct JointTarget_

typedef ::ob1_arm_control::JointTarget_<std::allocator<void> > JointTarget;

typedef boost::shared_ptr< ::ob1_arm_control::JointTarget > JointTargetPtr;
typedef boost::shared_ptr< ::ob1_arm_control::JointTarget const> JointTargetConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ob1_arm_control::JointTarget_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ob1_arm_control::JointTarget_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ob1_arm_control::JointTarget_<ContainerAllocator1> & lhs, const ::ob1_arm_control::JointTarget_<ContainerAllocator2> & rhs)
{
  return lhs.joint_target == rhs.joint_target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ob1_arm_control::JointTarget_<ContainerAllocator1> & lhs, const ::ob1_arm_control::JointTarget_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ob1_arm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ob1_arm_control::JointTarget_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ob1_arm_control::JointTarget_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ob1_arm_control::JointTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ob1_arm_control::JointTarget_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ob1_arm_control::JointTarget_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ob1_arm_control::JointTarget_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ob1_arm_control::JointTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "133ac1ee056e983bab7d9619a1e96ecf";
  }

  static const char* value(const ::ob1_arm_control::JointTarget_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x133ac1ee056e983bULL;
  static const uint64_t static_value2 = 0xab7d9619a1e96ecfULL;
};

template<class ContainerAllocator>
struct DataType< ::ob1_arm_control::JointTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ob1_arm_control/JointTarget";
  }

  static const char* value(const ::ob1_arm_control::JointTarget_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ob1_arm_control::JointTarget_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_target\n"
;
  }

  static const char* value(const ::ob1_arm_control::JointTarget_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ob1_arm_control::JointTarget_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointTarget_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ob1_arm_control::JointTarget_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ob1_arm_control::JointTarget_<ContainerAllocator>& v)
  {
    s << indent << "joint_target[]" << std::endl;
    for (size_t i = 0; i < v.joint_target.size(); ++i)
    {
      s << indent << "  joint_target[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_target[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OB1_ARM_CONTROL_MESSAGE_JOINTTARGET_H
