
classdef RelaxedIKServiceResponse < ros.Message
    %RelaxedIKServiceResponse MATLAB implementation of relaxed_ik/RelaxedIKServiceResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'relaxed_ik/RelaxedIKServiceResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f7b6cdcd8a9f344d4fe1265742fac728' % The MD5 Checksum of the message definition
        PropertyList = { 'JointAngles' } % List of non-constant message properties
        ROSPropertyList = { 'joint_angles' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.relaxed_ik.JointAngles' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        JointAngles
    end
    methods
        function set.JointAngles(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.relaxed_ik.JointAngles'};
            validateattributes(val, validClasses, validAttributes, 'RelaxedIKServiceResponse', 'JointAngles')
            obj.JointAngles = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.relaxed_ik.RelaxedIKServiceResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.relaxed_ik.RelaxedIKServiceResponse(strObj);
        end
    end
end
