
classdef RelaxedIKServiceRequest < ros.Message
    %RelaxedIKServiceRequest MATLAB implementation of relaxed_ik/RelaxedIKServiceRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'relaxed_ik/RelaxedIKServiceRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1fa9b22ae31214968e5d110b292dc65e' % The MD5 Checksum of the message definition
        PropertyList = { 'PoseGoals' } % List of non-constant message properties
        ROSPropertyList = { 'pose_goals' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.relaxed_ik.EEPoseGoals' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        PoseGoals
    end
    methods
        function set.PoseGoals(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.relaxed_ik.EEPoseGoals'};
            validateattributes(val, validClasses, validAttributes, 'RelaxedIKServiceRequest', 'PoseGoals')
            obj.PoseGoals = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.relaxed_ik.RelaxedIKServiceRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.relaxed_ik.RelaxedIKServiceRequest(strObj);
        end
    end
end
