// Generated by gencpp from file ob1_arm_control/MatlabIKServiceResponse.msg
// DO NOT EDIT!


#ifndef OB1_ARM_CONTROL_MESSAGE_MATLABIKSERVICERESPONSE_H
#define OB1_ARM_CONTROL_MESSAGE_MATLABIKSERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ob1_arm_control
{
template <class ContainerAllocator>
struct MatlabIKServiceResponse_
{
  typedef MatlabIKServiceResponse_<ContainerAllocator> Type;

  MatlabIKServiceResponse_()
    : result()
    , error(0.0)
    , joints()  {
    }
  MatlabIKServiceResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , error(0.0)
    , joints(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;

   typedef double _error_type;
  _error_type error;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _joints_type;
  _joints_type joints;





  typedef boost::shared_ptr< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MatlabIKServiceResponse_

typedef ::ob1_arm_control::MatlabIKServiceResponse_<std::allocator<void> > MatlabIKServiceResponse;

typedef boost::shared_ptr< ::ob1_arm_control::MatlabIKServiceResponse > MatlabIKServiceResponsePtr;
typedef boost::shared_ptr< ::ob1_arm_control::MatlabIKServiceResponse const> MatlabIKServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator1> & lhs, const ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.error == rhs.error &&
    lhs.joints == rhs.joints;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator1> & lhs, const ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ob1_arm_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bec3ec873883402ec62934e02f51a48f";
  }

  static const char* value(const ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbec3ec873883402eULL;
  static const uint64_t static_value2 = 0xc62934e02f51a48fULL;
};

template<class ContainerAllocator>
struct DataType< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ob1_arm_control/MatlabIKServiceResponse";
  }

  static const char* value(const ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"float64 error\n"
"float64[] joints\n"
;
  }

  static const char* value(const ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.error);
      stream.next(m.joints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MatlabIKServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ob1_arm_control::MatlabIKServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
    s << indent << "error: ";
    Printer<double>::stream(s, indent + "  ", v.error);
    s << indent << "joints[]" << std::endl;
    for (size_t i = 0; i < v.joints.size(); ++i)
    {
      s << indent << "  joints[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OB1_ARM_CONTROL_MESSAGE_MATLABIKSERVICERESPONSE_H
