// Generated by gencpp from file ob1_arm_control/MatlabIKService.msg
// DO NOT EDIT!


#ifndef OB1_ARM_CONTROL_MESSAGE_MATLABIKSERVICE_H
#define OB1_ARM_CONTROL_MESSAGE_MATLABIKSERVICE_H

#include <ros/service_traits.h>


#include <ob1_arm_control/MatlabIKServiceRequest.h>
#include <ob1_arm_control/MatlabIKServiceResponse.h>


namespace ob1_arm_control
{

struct MatlabIKService
{

typedef MatlabIKServiceRequest Request;
typedef MatlabIKServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MatlabIKService
} // namespace ob1_arm_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ob1_arm_control::MatlabIKService > {
  static const char* value()
  {
    return "f08a5cc5dd30424dbb2b2233c5f13b8e";
  }

  static const char* value(const ::ob1_arm_control::MatlabIKService&) { return value(); }
};

template<>
struct DataType< ::ob1_arm_control::MatlabIKService > {
  static const char* value()
  {
    return "ob1_arm_control/MatlabIKService";
  }

  static const char* value(const ::ob1_arm_control::MatlabIKService&) { return value(); }
};


// service_traits::MD5Sum< ::ob1_arm_control::MatlabIKServiceRequest> should match
// service_traits::MD5Sum< ::ob1_arm_control::MatlabIKService >
template<>
struct MD5Sum< ::ob1_arm_control::MatlabIKServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ob1_arm_control::MatlabIKService >::value();
  }
  static const char* value(const ::ob1_arm_control::MatlabIKServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ob1_arm_control::MatlabIKServiceRequest> should match
// service_traits::DataType< ::ob1_arm_control::MatlabIKService >
template<>
struct DataType< ::ob1_arm_control::MatlabIKServiceRequest>
{
  static const char* value()
  {
    return DataType< ::ob1_arm_control::MatlabIKService >::value();
  }
  static const char* value(const ::ob1_arm_control::MatlabIKServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ob1_arm_control::MatlabIKServiceResponse> should match
// service_traits::MD5Sum< ::ob1_arm_control::MatlabIKService >
template<>
struct MD5Sum< ::ob1_arm_control::MatlabIKServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ob1_arm_control::MatlabIKService >::value();
  }
  static const char* value(const ::ob1_arm_control::MatlabIKServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ob1_arm_control::MatlabIKServiceResponse> should match
// service_traits::DataType< ::ob1_arm_control::MatlabIKService >
template<>
struct DataType< ::ob1_arm_control::MatlabIKServiceResponse>
{
  static const char* value()
  {
    return DataType< ::ob1_arm_control::MatlabIKService >::value();
  }
  static const char* value(const ::ob1_arm_control::MatlabIKServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OB1_ARM_CONTROL_MESSAGE_MATLABIKSERVICE_H
