# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop

generic_hw_control_loop:
  loop_hz: 200 # 250 to emulate serial pause COMMAND_PERIOD 0.0055 , SERIAL_PAUSE 0.004
  cycle_time_error_threshold: 0.1

# Settings for ros_control hardware interface (used in generic_hw_interface.cpp)
hardware_interface:
   joints:
      - ob1_arm_fixed_base_joint
      - ob1_arm_base_shoulder_joint
      - ob1_arm_shoulder_arm_joint
      - ob1_arm_arm_elbow_joint
      - ob1_arm_elbow_forearm_joint
      - ob1_arm_forearm_gripper_joint

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 200

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   # These joints can likely just be copied from the hardware_interface list above
   joints:
      - ob1_arm_fixed_base_joint
      - ob1_arm_base_shoulder_joint
      - ob1_arm_shoulder_arm_joint
      - ob1_arm_arm_elbow_joint
      - ob1_arm_elbow_forearm_joint
      - ob1_arm_forearm_gripper_joint
  