// Generated by gencpp from file relaxed_ik/JointAngles.msg
// DO NOT EDIT!


#ifndef RELAXED_IK_MESSAGE_JOINTANGLES_H
#define RELAXED_IK_MESSAGE_JOINTANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/Float32.h>

namespace relaxed_ik
{
template <class ContainerAllocator>
struct JointAngles_
{
  typedef JointAngles_<ContainerAllocator> Type;

  JointAngles_()
    : header()
    , angles()  {
    }
  JointAngles_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , angles(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::std_msgs::Float32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::Float32_<ContainerAllocator> >::other >  _angles_type;
  _angles_type angles;





  typedef boost::shared_ptr< ::relaxed_ik::JointAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::relaxed_ik::JointAngles_<ContainerAllocator> const> ConstPtr;

}; // struct JointAngles_

typedef ::relaxed_ik::JointAngles_<std::allocator<void> > JointAngles;

typedef boost::shared_ptr< ::relaxed_ik::JointAngles > JointAnglesPtr;
typedef boost::shared_ptr< ::relaxed_ik::JointAngles const> JointAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::relaxed_ik::JointAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::relaxed_ik::JointAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::relaxed_ik::JointAngles_<ContainerAllocator1> & lhs, const ::relaxed_ik::JointAngles_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.angles == rhs.angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::relaxed_ik::JointAngles_<ContainerAllocator1> & lhs, const ::relaxed_ik::JointAngles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace relaxed_ik

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::relaxed_ik::JointAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::relaxed_ik::JointAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::relaxed_ik::JointAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::relaxed_ik::JointAngles_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::relaxed_ik::JointAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::relaxed_ik::JointAngles_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::relaxed_ik::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d19a5bafff81501c7a05b5f8ee0a31e";
  }

  static const char* value(const ::relaxed_ik::JointAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d19a5bafff81501ULL;
  static const uint64_t static_value2 = 0xc7a05b5f8ee0a31eULL;
};

template<class ContainerAllocator>
struct DataType< ::relaxed_ik::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "relaxed_ik/JointAngles";
  }

  static const char* value(const ::relaxed_ik::JointAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::relaxed_ik::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"std_msgs/Float32[] angles\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float32\n"
"float32 data\n"
;
  }

  static const char* value(const ::relaxed_ik::JointAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::relaxed_ik::JointAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::relaxed_ik::JointAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::relaxed_ik::JointAngles_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "    ", v.angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RELAXED_IK_MESSAGE_JOINTANGLES_H
