arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ob1_arm_fixed_base_joint
    - ob1_arm_base_shoulder_joint
    - ob1_arm_shoulder_arm_joint
    - ob1_arm_arm_elbow_joint
    - ob1_arm_elbow_forearm_joint
    - ob1_arm_forearm_gripper_joint
  gains:
    ob1_arm_fixed_base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ob1_arm_base_shoulder_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ob1_arm_shoulder_arm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ob1_arm_arm_elbow_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ob1_arm_elbow_forearm_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ob1_arm_forearm_gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ob1_arm_gripper_lclaw_joint
    - ob1_arm_gripper_rclaw_joint
  gains:
    ob1_arm_gripper_lclaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    ob1_arm_gripper_rclaw_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1