
classdef armState < ros.Message
    %armState MATLAB implementation of ob1_arm_hw_interface/armState
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ob1_arm_hw_interface/armState' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ce5e1d1c8004370004acde6f8290eea8' % The MD5 Checksum of the message definition
        PropertyList = { 'Angle' 'Vel' 'MsgRcvCtr' 'BufferHealth' } % List of non-constant message properties
        ROSPropertyList = { 'angle' 'vel' 'msg_rcv_ctr' 'buffer_health' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Angle
        Vel
        MsgRcvCtr
        BufferHealth
    end
    methods
        function set.Angle(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 6};
            validateattributes(val, validClasses, validAttributes, 'armState', 'Angle');
            obj.Angle = single(val);
        end
        function set.Vel(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 6};
            validateattributes(val, validClasses, validAttributes, 'armState', 'Vel');
            obj.Vel = single(val);
        end
        function set.MsgRcvCtr(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'armState', 'MsgRcvCtr');
            obj.MsgRcvCtr = int32(val);
        end
        function set.BufferHealth(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'armState', 'BufferHealth');
            obj.BufferHealth = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ob1_arm_hw_interface.armState.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ob1_arm_hw_interface.armState(strObj);
        end
    end
end
