controller_list:
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - ob1_arm_gripper_lclaw_joint
      - ob1_arm_gripper_rclaw_joint
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - ob1_arm_fixed_base_joint
      - ob1_arm_base_shoulder_joint
      - ob1_arm_shoulder_arm_joint
      - ob1_arm_arm_elbow_joint
      - ob1_arm_elbow_forearm_joint
      - ob1_arm_forearm_gripper_joint
initial:  # Define initial robot poses per group
  - group: gripper
    pose: gripper_open
  - group: arm
    pose: pose0